version: '3.1'

services:
  app:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DBNAME: springboot_scaffold
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 12345678
    ports:
      - "80:8080"

  db:
    image: mysql:8.0.35
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: springboot_scaffold
      MYSQL_ROOT_PASSWORD: 12345678
    volumes:
      - db:/var/lib/mysql

volumes:
  app:
  db: